
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.arbol_activacion.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_A = 11;
  public static final int INTEGER = 14;
  public static final int PROGRAMA = 7;
  public static final int SEMI = 13;
  public static final int EOF = 0;
  public static final int NUMERO = 9;
  public static final int ID = 8;
  public static final int DOT = 2;
  public static final int IGUAL = 3;
  public static final int error = 1;
  public static final int SEMICOLON = 10;
  public static final int PROCEDIMIENTO = 4;
  public static final int END = 6;
  public static final int BEGIN = 5;
  public static final int PAR_C = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOT",
  "IGUAL",
  "PROCEDIMIENTO",
  "BEGIN",
  "END",
  "PROGRAMA",
  "ID",
  "NUMERO",
  "SEMICOLON",
  "PAR_A",
  "PAR_C",
  "SEMI",
  "INTEGER"
  };
}

